dev:
  hosts:
    192.168.50.130:
  vars:
    ansible_user: root
    ansible_port: 22
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    INTRANET_IP: "192.168.50.130"
    INTERNET_IP: "192.168.50.130"

