pro:
  hosts:
     192.168.191.61:
#    60.204.170.61:
      ansible_python_interpreter: /usr/bin/python3.10
#    192.168.191.61:
  vars:
    ansible_user: root
    ansible_port: 22
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    INTRANET_IP: "60.204.170.61"
    INTERNET_IP: "60.204.170.61"

dev:
  hosts:
    192.168.50.130:
  vars:
    ansible_user: root
    ansible_port: 22
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    INTRANET_IP: "192.168.50.130"
    INTERNET_IP: "192.168.50.130"

