- name: Generate and encode VLESS link
  block:
    - name: Construct VLESS link parts
      ansible.builtin.set_fact:
        base_url: "vless://{{ uuid }}@{{ INTERNET_IP }}:{{ v2ray_port }}"
        query_params: >-
          type={{ v2ray_network | default('ws') }}&path={{ ws_path | default('/v2ray') | urlencode }}&host={{ INTERNET_IP }}&security=tls&sni={{ domain }}#My Default Server
      vars:
        query_params: "{{ query_params | replace('\n', '') | replace(' ', '') }}"

    - name: Build final VLESS link
      ansible.builtin.set_fact:
        vless_final_link: "{{ base_url }}?{{ query_params }}"

    - name: Display Base64 encoded VLESS link
      ansible.builtin.debug:
        msg: |
          链接: {{ vless_final_link }}