- name: 安装gcc/git等
  when:
    - ansible_facts["distribution"] == "CentOS"
  yum:
    name:
      - gcc
      - git
    state: present

- name: 删掉golang的tgz
  ansible.builtin.copy:
    src: "{{ GOLANG_TGZ }}"
    dest: /tmp/go.tar.gz
    mode: u=r,g=r,o=r

- name: Unarchive golang
  ansible.builtin.unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/local/go/bin/go
    dest: /usr/local/bin/go
    state: link
